const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`<!doctype html><div data-rnl-course-editor><form id="rnl-course-editor"><input name="id" value="12"><input name="version" value="7"><input name="data[registration_url]" value=""><select name="data[level_id]"><option value="0">Velg nivå</option><option value="101">Nybegynner</option><option value="102">Øvet 1</option></select><input name="data[title]" value="Unsaved local title"><select name="data[weekday]"><option value="1">Mandag</option><option value="2" selected>Tirsdag</option></select><input name="data[start_time]" value="18:00"><input name="data[end_time]" value="19:00"><input name="data[session_count]" value="2"><input name="data[room_id]" value="77"><input name="data[price_minor]" value="900"><input type="checkbox" name="data[price_from]"><select name="data[price_basis]"><option value="person">Per person</option><option value="pair" selected>Per par</option></select><input name="data[registration_from]"><input name="data[registration_until]"><select name="data[registration_status]"><option value="later">Senere</option><option value="available">Tilgjengelig</option></select></form><input form="rnl-course-editor" name="data[first_date]"><input form="rnl-course-editor" name="data[timezone]" value="Europe/Oslo"><div data-break-row><input type="checkbox"><input data-field="from" value="2031-01-20"><input data-field="until" value=""></div><form id="other"><input name="id" value="99"><input name="version" value="2"></form>
<div hidden data-rnl-letsreg-picker data-id="12" data-version="7" data-registration-url="" data-nonce="test-nonce" data-url="http://localhost/admin-ajax.php">
<div data-saved-summary>Old mapping</div><details data-editor open><form data-search-form><input type="checkbox" role="switch" name="period_only" checked><input name="query" value="Salsa Øvet"><button>Search</button></form><div data-results></div>
<form data-mapping-form hidden><h4 data-event-name tabindex="-1"></h4><input name="event_id" type="hidden"><input name="verification_id" type="hidden"><div data-url-preview hidden><a data-event-url></a><p data-url-difference></p><input type="checkbox" name="use_api_url" value="1"></div><p data-url-missing hidden></p><div data-categories></div><div data-course-suggestions hidden></div><button>Save</button><button type="button" data-cancel>Cancel</button></form></details>
<details data-remove-panel hidden><button type="button" data-remove>Remove</button></details><p data-message role="status" tabindex="-1"></p></div>`, { url: 'http://localhost/editor', runScripts: 'outside-only' });
const w = dom.window;
w.wp = { i18n: { __: (text) => text } };
const calls = []; const replies = [];
w.fetch = async (url, options) => {
    calls.push({ url, body: Object.fromEntries(options.body.entries()) });
    const next = replies.shift(); assert.ok(next, 'Unexpected request');
    if (next instanceof Error) throw next;
    return { ok: next.success !== false, json: async () => next };
};
w.eval(fs.readFileSync('plugin/reginor-lite/assets/letsreg-picker.js', 'utf8'));
const $ = (s) => w.document.querySelector(s);
const url = $('#rnl-course-editor [name="data[registration_url]"]');
const form = $('[data-mapping-form]');
const tick = () => new Promise((resolve) => setImmediate(resolve));
const submit = async (el) => { el.dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true })); await tick(); };
const click = async (el) => { el.click(); await tick(); };
const choose = async () => { const select = $('[data-results] select'); select.value = '5'; select.dispatchEvent(new w.Event('change')); await tick(); }; 
const providerUrl = 'https://www.letsreg.com/event/checked';
const selected = (eventUrl = providerUrl) => ({ success: true, data: { event_id: 5, event_name: 'Salsa Øvet', verification_id: 'proof', event_url: eventUrl,
    html: '<select name="data[categories][1][role]"><option value="">Ikke med på dette kurset</option><option value="leader" selected>Fører</option></select><select name="data[categories][1][registration]"><option value="single">Enkeltpåmelding</option><option value="pair" selected>Parpåmelding – per deltaker</option></select>' } });
const saved = (version, registrationUrl = providerUrl, linked = true) => ({ success: true, data: { version, registration_url: registrationUrl, linked, html: '<p>Saved mapping</p>', message: 'Saved' } });
(async () => {
    assert.equal(calls.length, 0, 'Page loading must not call provider');
    assert.equal($('[data-rnl-letsreg-picker]').hidden, false);
    replies.push({ success: true, data: { period: { start: '2031-01-06', end: '2031-02-10' }, events: [{ id: 5, name: '<img src=x onerror=alert(1)>', start_on: '2031-01-06', start_label: '06.01.2031', active: true, isCancelled: false }, { id: 6, name: 'Outside', start_on: '2031-02-11', start_label: '11.02.2031', active: true }, { id: 7, name: 'No date', active: true }, { id: 8, name: 'Last day', start_on: '2031-02-10', start_label: '10.02.2031', active: true }], has_more: true } });
    await submit($('[data-search-form]'));
    assert.equal(calls[0].body.query, 'Salsa Øvet');
    assert.equal(calls[0].body.operation, 'search');
    assert.equal($('[data-results] img'), null, 'Provider names must be text');
    assert.equal($('[data-results] ul'), null, 'Long result list is still rendered');
    assert.equal($('[data-results] select').options.length, 3, 'Filter must include both boundary days only');
    assert.match($('[data-results] option[value="5"]').textContent, /Oppstart: 06.01.2031/);
    const toggle = $('[name="period_only"]'); const beforeToggle = calls.length;
    toggle.checked = false; toggle.dispatchEvent(new w.Event('change'));
    assert.equal($('[data-results] select').options.length, 5);
    assert.match($('[data-results] option[value="7"]').textContent, /Oppstart ikke oppgitt/);
    toggle.checked = true; toggle.dispatchEvent(new w.Event('change'));
    assert.equal(calls.length, beforeToggle, 'Toggling filter should reuse fetched results');
    replies.push({ success: true, data: { period: { start: '2031-01-06', end: '2031-02-10' }, events: [{ id: 9, name: 'Another page', start_on: '2031-01-20', start_label: '20.01.2031', active: true }], has_more: false } });
    await click($('[data-results] button'));
    assert.equal(calls.at(-1).body.offset, '20');
    assert.ok($('[data-results] option[value="5"]') && $('[data-results] option[value="9"]'), 'More results discard earlier matches');
    assert.equal($('[data-results] button'), null, 'Load-more remains after last page');
    replies.push(selected()); await choose();
    assert.equal(form.hidden, false);
    assert.equal($('[data-results] select').value, '5', 'Selected result is not retained in compact dropdown');
    assert.equal(url.value, providerUrl, 'Empty registration URL not autofilled');
    assert.equal(form.elements.use_api_url.checked, true);
    assert.equal(w.document.activeElement, $('[data-event-name]'));
    assert.equal($('#rnl-course-editor [name="data[title]"]').value, 'Unsaved local title');
    // Refreshing the same event must not undo manual changes or restore excluded categories.
    form.elements.namedItem('data[categories][1][role]').value = '';
    form.elements.namedItem('data[categories][1][registration]').value = 'single';
    replies.push(selected()); await choose();
    assert.equal(form.elements.namedItem('data[categories][1][role]').value, '', 'Refresh reselects excluded category');
    assert.equal(form.elements.namedItem('data[categories][1][registration]').value, 'single', 'Refresh replaces manual registration form');
    form.elements.namedItem('data[categories][1][role]').value = 'leader';
    form.elements.namedItem('data[categories][1][registration]').value = 'pair';
    const unload = new w.Event('beforeunload', { cancelable: true }); w.dispatchEvent(unload);
    assert.equal(unload.defaultPrevented, true, 'Pending mapping can be silently discarded');
    replies.push(saved(8)); await submit(form);
    assert.equal(calls.at(-1).body.use_api_url, '1');
    assert.equal(calls.at(-1).body['data[categories][1][registration]'], 'pair');
    assert.equal($('#rnl-course-editor [name="version"]').value, '8');
    assert.equal($('#other [name="version"]').value, '2');
    assert.equal($('#rnl-course-editor [name="data[title]"]').value, 'Unsaved local title');
    assert.equal(form.hidden, true);
    const clean = new w.Event('beforeunload', { cancelable: true }); w.dispatchEvent(clean); assert.equal(clean.defaultPrevented, false);
    url.value = 'https://www.letsreg.com/event/my-unsaved-choice';
    replies.push(selected()); await choose();
    assert.equal(form.elements.use_api_url.checked, false, 'Existing URL silently selected for replacement');
    assert.equal(url.value, 'https://www.letsreg.com/event/my-unsaved-choice');
    assert.match($('[data-url-difference]').textContent, /my-unsaved-choice/);
    form.elements.use_api_url.checked = true; form.elements.use_api_url.dispatchEvent(new w.Event('change'));
    assert.equal(url.value, providerUrl);
    await click($('[data-cancel]')); assert.equal(url.value, 'https://www.letsreg.com/event/my-unsaved-choice');
    replies.push(selected()); await choose();
    replies.push({ success: false, data: { message: 'Version conflict' } }); await submit(form);
    assert.equal(form.hidden, false, 'Failed save discards chosen categories');
    assert.equal($('#rnl-course-editor [name="version"]').value, '8');
    assert.equal($('[data-message]').getAttribute('role'), 'alert');
    assert.equal(w.document.activeElement, $('[data-message]'));
    assert.equal($('[data-mapping-form] button').disabled, false, 'Error leaves form disabled');
    replies.push(selected(null)); await choose();
    assert.equal($('[data-url-missing]').hidden, false);
    assert.equal(form.elements.use_api_url.checked, false);
    assert.equal(url.value, 'https://www.letsreg.com/event/my-unsaved-choice');
    replies.push(saved(9, null)); await submit(form);
    assert.equal(calls.at(-1).body.use_api_url, undefined);
    assert.equal(url.value, 'https://www.letsreg.com/event/my-unsaved-choice');
    replies.push(saved(10, null, false)); await click($('[data-remove]'));
    assert.equal($('[data-remove-panel]').hidden, true);
    assert.equal($('#rnl-course-editor [name="version"]').value, '10');
    assert.equal(url.value, 'https://www.letsreg.com/event/my-unsaved-choice');
    url.value = '';
    replies.push(selected()); await choose();
    url.value = 'https://www.letsreg.com/event/manual-change'; url.dispatchEvent(new w.Event('input', { bubbles: true }));
    assert.equal(form.elements.use_api_url.checked, false, 'Manual URL change still selects API overwrite');
    await click($('[data-cancel]'));
    assert.equal(url.value, 'https://www.letsreg.com/event/manual-change', 'Cancel loses manual URL edit');
    const event = selected(); event.data.suggestions = {
        fields: { level_id: 101, title: 'Navn hos LetsReg', weekday: '1', start_time: '18:30', end_time: '20:00', first_date: '2031-01-06', registration_from: '2030-12-01T01:00', registration_until: '2031-01-12T23:00', registration_status: 'available' },
        start_date: '2031-01-06', end_date: '2031-02-10', timezone: 'Europe/Oslo', period_breaks: [{ from: '2031-01-13', until: '2031-01-13' }], prices: [{ id: 1, price_minor: 75050 }]
    };
    replies.push(event); await choose();
    const editor = $('#rnl-course-editor'); const field = key => editor.elements.namedItem('data[' + key + ']');
    assert.equal(field('title').value, 'Unsaved local title', 'Suggestions overwrite without apply');
    assert.equal(field('level_id').value, '0', 'Level written before applying suggestions');
    assert.match($('[data-suggestion="level_id"]').parentElement.textContent, /Kursnivå: Nybegynner/);
    assert.equal($('[data-suggestion="session_count"]').parentElement.textContent.includes('4'), true, 'Weekly estimate ignores period/course breaks');
    $('[data-suggestion="title"]').checked = false;
    await click($('[data-course-suggestions] button'));
    assert.equal(field('title').value, 'Unsaved local title', 'Unchecked suggestion overwrites title');
    assert.equal(field('level_id').value, '101', 'Matched level not applied');
    assert.equal(field('start_time').value, '18:30'); assert.equal(field('end_time').value, '20:00');
    assert.equal(field('first_date').value, '2031-01-06', 'External first date is not filled');
    assert.equal(field('session_count').value, '4'); assert.equal(field('room_id').value, '77');
    assert.equal(field('registration_status').value, 'later', 'Existing manual status overwritten');
    $('[data-suggestion="registration_status"]').checked = true;
    await click($('[data-course-suggestions] button'));
    assert.equal(field('registration_status').value, 'available');
    assert.equal(field('registration_until').value, '2031-01-12T23:00');
    await click($('[data-course-suggestions] button:last-child'));
    assert.equal(field('price_minor').value, '750,50'); assert.equal(field('price_basis').value, 'person');
    assert.equal(field('price_from').checked, true, 'Minimum price is not labelled as from-price');
    const submitted = new w.FormData(editor);
    assert.equal(submitted.get('data[first_date]'), '2031-01-06', 'External first date absent from submitted form');
    // An existing choice and later manual changes require an explicit opt-in to replacement.
    field('level_id').value = '102';
    replies.push(event); await choose();
    assert.equal($('[data-suggestion="level_id"]').checked, false);
    await click($('[data-course-suggestions] button'));
    assert.equal(field('level_id').value, '102', 'Existing level overwritten');
    $('[data-suggestion="level_id"]').checked = true;
    await click($('[data-course-suggestions] button'));
    assert.equal(field('level_id').value, '101', 'Explicit replacement ignored');
    field('level_id').value = '0';
    replies.push(event); await choose();
    assert.equal($('[data-suggestion="level_id"]').checked, true);
    field('level_id').value = '102'; field('level_id').dispatchEvent(new w.Event('change', { bubbles: true }));
    await click($('[data-course-suggestions] button'));
    assert.equal(field('level_id').value, '102', 'Manual edit after lookup overwritten');
    field('level_id').value = '0'; field('level_id').dispatchEvent(new w.Event('change', { bubbles: true }));
    await click($('[data-course-suggestions] button'));
    assert.equal(field('level_id').value, '0', 'Manual removal overwritten');
    const noMatch = structuredClone(event); delete noMatch.data.suggestions.fields.level_id;
    replies.push(noMatch); await choose();
    assert.equal($('[data-suggestion="level_id"]'), null);
    assert.match($('[data-course-suggestions]').textContent, /ikke ett entydig treff/);
    field('timezone').value = 'UTC'; field('start_time').value = '21:00';
    await click($('[data-course-suggestions] button'));
    assert.equal(field('start_time').value, '21:00', 'Stale timezone suggestion applied');
    replies.push({ success: true, data: { period: { start: '2040-01-01', end: '2040-02-01' }, events: [{ id: 5, name: 'Outside', start_on: '2031-01-06', start_label: '06.01.2031', active: true }], has_more: true } });
    await submit($('[data-search-form]'));
    assert.equal($('[data-results] select').disabled, true, 'Empty filtered page still offers selection');
    assert.ok($('[data-results] button'), 'Filtering a page removed access to remaining results');
    assert.match($('[data-results]').textContent, /blant de hentede/);
    toggle.checked = false; toggle.dispatchEvent(new w.Event('change'));
    assert.equal($('[data-results] select').disabled, false, 'Turning filter off cannot reveal fetched outside dates');
    replies.push({ success: false, data: { message: 'Provider error' } }); await choose();
    assert.equal($('[data-results] select').value, '', 'Failed selection cannot be retried');
    assert.equal(replies.length, 0);
    dom.window.close();
    console.log('Inline LetsReg DOM journey passed: selection, URL autofill/replacement, cancellation, errors, retained edits and version updates.');
})().catch((error) => { dom.window.close(); console.error(error); process.exitCode = 1; });
